version: '3.9'
services:
  glances:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    environment:
      GLANCES_OPT: "-C /glances/conf/glances.conf -w"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf"
    pid: "host"
    privileged: true
