name: ci

on:
    pull_request:
      branches: [ develop ]
    push:
      branches: [ master, develop ]
      tags:
        - v*

jobs:
    quality:
      uses: ./.github/workflows/quality.yml
    test:
      uses: ./.github/workflows/test.yml
      needs: quality
    webui:
      if: ${{ always() }}
      uses: ./.github/workflows/webui.yml
      needs: [quality, test]
    build:
      uses: ./.github/workflows/build.yml
      secrets:
        TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      needs: [quality, test, webui]
