name: ci

on:
    pull_request:
      branches: [ develop ]
    push:
      branches: [ master, develop ]
      tags:
        - v*

jobs:
    quality:
      uses: ./.github/workflows/quality.yml
    test:
      uses: ./.github/workflows/test.yml
      needs: quality
    webui:
      if: ${{ always() }}
      uses: ./.github/workflows/webui.yml
      needs: [quality, test]
    build:
      uses: ./.github/workflows/build.yml
      needs: [quality, test, webui]
